routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {
  Route::get('/home', 'HomeController@index')->name('home');

  Route::get('export', 'ExcelController@Export');

  Route::get('penelitian/excel/{type}', 'ExcelController@penelitian');

  Route::get('pengabdian/excel/{type}', 'ExcelController@pengabdian');

  Route::get('dosen/excel/{type}', 'ExcelController@dosen');

  Route::get('penunjang/excel/{type}', 'ExcelController@penunjang');

  Route::get('dupak/excel/{type}', 'ExcelController@dupak');

  Route::put('detail_penunjang/{id}', 'PenunjangController@update_detail');

  Route::delete('detail_penunjang/{id}', 'PenunjangController@destroy_detail');

  Route::put('detail_unsurpendidikan/{id}', 'UnsurPendidikanController@update_detail');

  Route::delete('detail_unsurpendidikan/{id}', 'UnsurPendidikanController@destroy_detail');

  Route::put('detail_pelaksanapendidikan/{id}', 'PelaksanaPendidikanController@update_detail');

  Route::delete('detail_pelaksanapendidikan/{id}', 'PelaksanaPendidikanController@destroy_detail');

  Route::put('detail_penelitian/{id}', 'PenelitianController@update_detail');

  Route::delete('detail_penelitian/{id}', 'PenelitianController@destroy_detail');

  Route::put('detail_pengabdian/{id}', 'PengabdianController@update_detail');

  Route::delete('detail_pengabdian/{id}', 'PengabdianController@destroy_detail');

  Route::post('penelitian/find', 'PenelitianController@find');

  Route::post('penunjang/find', 'PenunjangController@find');

  Route::post('pengabdian/find', 'PengabdianController@find');

  Route::post('unsurpendidikan/find', 'UnsurPendidikanController@find');

  Route::post('pelaksanapendidikan/find', 'PelaksanaPendidikanController@find');

  Route::resource('dosen', 'DosenController');

  Route::resource('penelitian_detail', 'DetailPenelitianController');

  Route::resource('unsurpendidikan', 'UnsurPendidikanController');

  Route::resource('pendidikan', 'PendidikanController');

  Route::resource('pelaksanapendidikan', 'PelaksanaPendidikanController');

  Route::resource('penelitian', 'PenelitianController');

  Route::resource('pengabdian', 'PengabdianController');

  Route::resource('penunjang', 'PenunjangController');

  Route::resource('dupak', 'DupakController');

  Route::get('penelitian/downloadPDF/{id}','PenelitianController@downloadPDF');

  Route::get('pengabdian/downloadPDF/{id}','PengabdianController@downloadPDF');

  Route::get('penunjang/downloadPDF/{id}','PenunjangController@downloadPDF');

  Route::get('pendidikan/downloadPDF/{id}','PendidikanController@downloadPDF');

  Route::get('dupak/downloadPDF/{id}','DupakController@downloadPDF');
});

app/Http/Controllers/DosenController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;

class DosenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::all();
        return view('dosen.index')->with('data', $data);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dosen.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $dosen = new User;
        $dosen->name = $request->input('name');
        $dosen->penanggung_jawab = $request->input('penanggung_jawab');
        $dosen->email = $request->input('email');
        $dosen->password = Hash::make('password');
        $dosen->nip = $request->input('nip');
        $dosen->nidn = $request->input('nidn');
        $dosen->no_karpeg = $request->input('no_karpeg');
        $dosen->ttl = $request->input('ttl');
        $dosen->jk = $request->input('jk');
        $dosen->pendidikan = $request->input('pendidikan');
        $dosen->pangkat = $request->input('pangkat');
        $dosen->gol_ruang = $request->input('gol_ruang');
        $dosen->jab_fungsional = $request->input('jab_fungsional');
        $dosen->tmt = $request->input('tmt');
        $dosen->fakultas = $request->input('fakultas');
        $dosen->jurusan = $request->input('jurusan');
        $dosen->masa_kerja = $request->input('masa_kerja');
        $dosen->unit_kerja = $request->input('unit_kerja');
        $dosen->save();
        $dosen->attachRole('dosen');

        return redirect(route('dosen.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = User::find($id);
         $a = User::where('id' , $data->penanggung_jawab)->get();
            return view('dosen.view',compact('data', 'a'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::findOrFail($id);
            return view('dosen.edit')->with('data', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $dosen = User::find($id);
        $dosen->name = $request->input('name');
        $dosen->penanggung_jawab = $request->input('penanggung_jawab');
        $dosen->email = $request->input('email');
        $dosen->password = Hash::make($request->input('password'));
        $dosen->nip = $request->input('nip');
        $dosen->nidn = $request->input('nidn');
        $dosen->no_karpeg = $request->input('no_karpeg');
        $dosen->ttl = $request->input('ttl');
        $dosen->jk = $request->input('jk');
        $dosen->pendidikan = $request->input('pendidikan');
        $dosen->pangkat = $request->input('pangkat');
        $dosen->gol_ruang = $request->input('gol_ruang');
        $dosen->jab_fungsional = $request->input('jab_fungsional');
        $dosen->tmt = $request->input('tmt');
        $dosen->fakultas = $request->input('fakultas');
        $dosen->jurusan = $request->input('jurusan');
        $dosen->masa_kerja = $request->input('masa_kerja');
        $dosen->unit_kerja = $request->input('unit_kerja');
        $dosen->save();

        return redirect('/dosen')->with('success', 'Dosen Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $id = User::find($id);
        $id->delete();
        return redirect('/dosen');
    }
}

resources/views/dosen/create.blade.php
@extends('layouts.app')
@section('content')
  <div class="column">
    <div class="card">
      <div class="card-header">
        <div class="columns">
          <div class="column">
            <p class="card-header-title">
              Tambah Data Dosen
            </p>
          </div>
        </div>
      </div>
      <div class="notification is-info"> Pastikan Semua Data Terisi</div>
      <div class="card-content">
        <form class="form-vertical" action="{{ route('dosen.store') }}" method="post">
          {{ csrf_field() }}
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Nama
                  <td><font color="red" class="is-subtitle"size="2">(*)</font></td>
                </label>
                <div class="control">
                  <input class="input" type="text" name="name">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Email
                  <td><font color="red" class="is-subtitle"size="2">(*)</font></td>
                </label>
                <div class="control">
                  <input class="input" type="text" name="email">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Password
                  <td><font class="is-subtitle"size="2">( Password dapat diubah melalui admin )</font></td>
                </label>
                <div class="control">
                  <input class="input" type="text" name="password" placeholder="Default Password : password" readonly>
                </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">NIP</label>
                <div class="control">
                  <input class="input" type="text" name="nip">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">NIDN</label>
                <div class="control">
                  <input class="input" type="text" name="nidn">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Nomor Seri KARPEG</label>
                <div class="control">
                   <input class="input" type="text" name="no_karpeg">
                </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Tempat dan Tanggal Lahir</label>
                <div class="control">
                  <input class="input" type="text" name="ttl">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Jenis Kelamin <font color="red" class="is-subtitle"size="2">(*)</font></label>
                <div class="control">
                  <div class="select">
                    <select name="jk" type="enum">
                      <option value="Jenis Kelamin">Jenis Kelamin</option>
                      <option value="Laki - Laki">Laki - Laki</option>
                      <option value="Perempuan">Perempuan</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
              <div class="column">
                <div class="field">
                  <label class="label">Pendidikan Tertinggi</label>
                  <div class="control">
                    <input class="input" type="text" name="pendidikan">
                  </div>
                </div>
              </div>
            </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Pangkat</label>
                <div class="control">
                  <input class="input" type="text" name="pangkat">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Golongan Ruang</label>
                <div class="control">
                  <input class="input" type="text" name="gol_ruang">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Jabatan Fungsional
                  <td><font color="red" class="is-subtitle"size="2">(*)</font></td>
                </label>
                <div class="control">
                  <div class="select">
                    <select name="jab_fungsional" type="enum">
                      <option value="Jabatan Fungsional">Jabatan Fungsional</option>
                      <option value="Asisten Ahli">Asisten Ahli</option>
                      <option value="Lektor">Lektor</option>
                      <option value="Lektor Kepala">Lektor Kepala</option>
                      <option value="Profesor">Profesor</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">TMT</label>
                <div class="control">
                  <input class="input" type="text" name="tmt">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Fakultas</label>
                <div class="control">
                  <input class="input" type="text" name="fakultas">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Jurusan</label>
                <div class="control">
                <input class="input" type="text" name="jurusan">
                </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Masa Kerja</label>
                <div class="control">
                  <input class="input" type="text" name="masa_kerja">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Unit Kerja</label>
                <div class="control">
                  <input class="input" type="text" name="unit_kerja">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Penanggung Jawab
                  <td><font color="red" class="is-subtitle"size="2">(*)</font></td>
                </label>
                  <div class="control">
                  <select class="input" type="text" name="penanggung_jawab" id="dosen"></select>
                  </div>

                  <td><font color="red" class="is-subtitle"size="2">Data Penanggung Jawab dapat diisi melalui form dosen</font></td>
              </div>
            </div>
          </div>
              <div class="columns m-t-30 is-gapless">
                <div class="column">
                  <a href="{{ route('dosen.index') }}"class="button is-danger">Cancel</a>
                </div>
                <div class="column">
                  <button class="button is-success" type="submit">Save</button>
                </div>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript">
 $('#dosen').select2({
    placeholder: 'Cari',
    ajax: {
      url: '/api/dosen/search',
      dataType: 'json',
      delay: 250,
      processResults: function (data) {
        return {
          results:  $.map(data, function (item) {
            return {
              text: item.name,
              id: item.id
            }
          })
        };
      },
      cache: true
    }
  });
  </script>
@endpush

@push('style')
  <style media="screen">

  </style>
@endpush

resources/views/dosen/edit.blade.php
@extends('layouts.app')
@section('content')
  <div class="column">
    <div class="card">
      <div class="card-header">
        <div class="columns">
          <div class="column">
            <p class="card-header-title">
              Edit Data Dosen
            </p>
          </div>
        </div>
      </div>
      <div class="notification is-info"> Pastikan Semua Data Terisi! </div>
      <div class="card-content">
        <form class="form-vertical" action="{{ url('dosen/'.$data->id) }}" method="post">
          {{ csrf_field() }}
          <input type="hidden" name="_method" value="PUT">
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Nama</label>
                <div class="control">
                  <input class="input" type="text" name="name" value="{{ $data->name }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Email <font color="red" class="is-subtitle"size="2">(*)</font></label>
                <div class="control">
                  <input class="input" type="text" name="email" value="{{ $data->email }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Password
                  <font color="red" class="is-subtitle"size="2">(*)</font>
                </label>
                <div class="control">
                  <input class="input" type="password" name="password" required>
                </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">NIP</label>
                <div class="control">
                  <input class="input" type="text" name="nip" value="{{ $data->nip }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">NIDN</label>
                <div class="control">
                  <input class="input" type="text" name="nidn" value="{{ $data->nidn }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Nomor Seri KARPEG</label>
                <div class="control">
                   <input class="input" type="text" name="no_karpeg" value="{{ $data->no_karpeg }}">
                </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Tempat dan Tanggal Lahir</label>
                <div class="control">
                  <input class="input" type="text" name="ttl" value="{{ $data->ttl }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Jenis Kelamin
                  <font color="red" class="is-subtitle"size="2">(*)</font>
                </label>
                <div class="control">
                  <div class="select">
                    <select name="jk" type="enum" value="{{ $data->jk }}">
                      <option value="Jenis Kelamin">Jenis Kelamin</option>
                      <option value="Laki - Laki">Laki - Laki</option>
                      <option value="Perempuan">Perempuan</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
              <div class="column">
                <div class="field">
                  <label class="label">Pendidikan Tertinggi</label>
                  <div class="control">
                    <input class="input" type="text" name="pendidikan" value="{{ $data->pendidikan }}">
                  </div>
                </div>
              </div>
            </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Pangkat</label>
                <div class="control">
                  <input class="input" type="text" name="pangkat" value="{{ $data->pangkat }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Golongan Ruang</label>
                <div class="control">
                  <input class="input" type="text" name="gol_ruang" value="{{ $data->gol_ruang }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Jabatan Fungsional
                  <font color="red" class="is-subtitle"size="2">(*)</font>
                </label>
                <div class="control">
                  <div class="select">
                    <select name="jab_fungsional" type="enum" value="{{ $data->jab_fungsional }}">
                      <option value="Jabatan Fungsional">Jabatan Fungsional</option>
                      <option value="Asisten Ahli">Asisten Ahli</option>
                      <option value="Lektor">Lektor</option>
                      <option value="Lektor Kepala">Lektor Kepala</option>
                      <option value="Profesor">Profesor</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">TMT</label>
                <div class="control">
                  <input class="input" type="text" name="tmt" value="{{ $data->tmt }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Fakultas</label>
                <div class="control">
                  <input class="input" type="text" name="fakultas" value="{{ $data->fakultas }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Jurusan</label>
                <div class="control">
                <input class="input" type="text" name="jurusan" value="{{ $data->jurusan }}">
                </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Masa Kerja</label>
                <div class="control">
                  <input class="input" type="text" name="masa_kerja" value="{{ $data->masa_kerja }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Unit Kerja</label>
                <div class="control">
                  <input class="input" type="text" name="unit_kerja" value="{{ $data->unit_kerja }}">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Penanggung Jawab
                  <font color="red" class="is-subtitle"size="2">(*)</font>
                </label>
                  <div class="control">
                  <select class="input" type="text" name="penanggung_jawab" id="dosen" value="{{ $data->penanggung_jawab }}"></select>
                  </div>
                  <td><font color="red" class="is-subtitle"size="2">Data Penanggung Jawab dapat diisi melalui form dosen</font></td>
              </div>
            </div>
          </div>
          <div class="columns m-t-30 is-gapless">
            <div class="column">
              <a href="{{ route('dosen.index') }}"class="button is-danger">Cancel</a>
            </div>
            <div class="column">
              <button class="button is-success" type="submit">Save</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript">
 $('#dosen').select2({
    placeholder: 'Cari',
    ajax: {
      url: '/api/dosen/search',
      dataType: 'json',
      delay: 250,
      processResults: function (data) {
        return {
          results:  $.map(data, function (item) {
            return {
              text: item.name,
              id: item.id
            }
          })
        };
      },
      cache: true
    }
  });
  </script>
@endpush

@push('style')
  <style media="screen">

  </style>
@endpush

resources/views/dosen/index.blade.php
@extends('layouts.app')

@section('content')
<div class="column">
    <div class="card">
        <div class="card-header">
                    <p class="card-header-title">
                    Data Dosen
                    </p>
          <div class="p-t-5 p-r-5">
            <a href="{{ URL::to('dosen/excel/xls') }}"class="button is-link">Download Excel XLS </a>
            <a href="{{ URL::to('dosen/excel/xlsx') }}"class="button is-info p-l-10">Download Excel XLSX </a>
            <a href="{{ URL::to('dosen/excel/csv') }}"class="button is-link p-l-10">Download Excel CSV </a>
          </div>
        </div>

        <div class="card-content table__wrapper">
        <div class="columns">
          <a href="{{ route('dosen.create') }}"class="button is-primary">Create</a>
        </div>
          <table class="table is-bordered pricing__table" id="datatable">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama</th>
                <th>NIP / NIDN</th>
                <th>Pangkat / Golongan Ruang</th>
                <th>Jabatan Fungsional</th>
                <th>Unit Kerja</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <?php $n=1 ?>
              @foreach($data as $a)
              <tr>
                <th>{{ $n }}</th>
                <td>{{ $a->name }}</td>
                <td>{{ $a->nip }} / {{ $a->nidn }} </td>
                <td>{{ $a->pangkat }} / {{ $a->gol_ruang }} </td>
                <td>{{ $a->jab_fungsional }}</td>
                <td>{{ $a->unit_kerja}}</td>
                <td>
                  <div class="columns">
                    <div class="column">
                      <a href="dosen/{{$a->id}}" class="button is-info">View</a>
                    </div>
                    <div class="column">
                      <form action="dosen/{{$a->id}}" method="post">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="delete">
                        <button type="submit" name="button" class="button is-danger">Delete</button>
                      </form>
                    </div>
                  </div>
                </td>
              </tr>
              <?php $n++ ?>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>
@endsection

@push('scripts')
  <script type="text/javascript">
    $('#datatable').DataTable();
  </script>
@endpush

@push('styles')
  <style media="screen">
    .pricing__table {
        width: 100%;
        overflow-x: auto;
    }

    .table__wrapper {
        overflow-x: auto;
    }
  </style>
@endpush