routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {
  Route::get('/home', 'HomeController@index')->name('home');

  Route::get('export', 'ExcelController@Export');

  Route::get('penelitian/excel/{type}', 'ExcelController@penelitian');

  Route::get('pengabdian/excel/{type}', 'ExcelController@pengabdian');

  Route::get('dosen/excel/{type}', 'ExcelController@dosen');

  Route::get('penunjang/excel/{type}', 'ExcelController@penunjang');

  Route::get('dupak/excel/{type}', 'ExcelController@dupak');

  Route::put('detail_penunjang/{id}', 'PenunjangController@update_detail');

  Route::delete('detail_penunjang/{id}', 'PenunjangController@destroy_detail');

  Route::put('detail_unsurpendidikan/{id}', 'UnsurPendidikanController@update_detail');

  Route::delete('detail_unsurpendidikan/{id}', 'UnsurPendidikanController@destroy_detail');

  Route::put('detail_pelaksanapendidikan/{id}', 'PelaksanaPendidikanController@update_detail');

  Route::delete('detail_pelaksanapendidikan/{id}', 'PelaksanaPendidikanController@destroy_detail');

  Route::put('detail_penelitian/{id}', 'PenelitianController@update_detail');

  Route::delete('detail_penelitian/{id}', 'PenelitianController@destroy_detail');

  Route::put('detail_pengabdian/{id}', 'PengabdianController@update_detail');

  Route::delete('detail_pengabdian/{id}', 'PengabdianController@destroy_detail');

  Route::post('penelitian/find', 'PenelitianController@find');

  Route::post('penunjang/find', 'PenunjangController@find');

  Route::post('pengabdian/find', 'PengabdianController@find');

  Route::post('unsurpendidikan/find', 'UnsurPendidikanController@find');

  Route::post('pelaksanapendidikan/find', 'PelaksanaPendidikanController@find');

  Route::resource('dosen', 'DosenController');

  Route::resource('penelitian_detail', 'DetailPenelitianController');

  Route::resource('unsurpendidikan', 'UnsurPendidikanController');

  Route::resource('pendidikan', 'PendidikanController');

  Route::resource('pelaksanapendidikan', 'PelaksanaPendidikanController');

  Route::resource('penelitian', 'PenelitianController');

  Route::resource('pengabdian', 'PengabdianController');

  Route::resource('penunjang', 'PenunjangController');

  Route::resource('dupak', 'DupakController');

  Route::get('penelitian/downloadPDF/{id}','PenelitianController@downloadPDF');

  Route::get('pengabdian/downloadPDF/{id}','PengabdianController@downloadPDF');

  Route::get('penunjang/downloadPDF/{id}','PenunjangController@downloadPDF');

  Route::get('pendidikan/downloadPDF/{id}','PendidikanController@downloadPDF');

  Route::get('dupak/downloadPDF/{id}','DupakController@downloadPDF');
});

app/Penunjang.php
<?php

namespace App;

use App\DetailPenunjang;
use Illuminate\Database\Eloquent\Model;

class Penunjang extends Model
{
    protected $table = 'penunjangs';

    protected $fillable = [
        'user_id',
        'name',
        'nip',
        'nidn',
        'pangkat',
        'gol_ruang',
        'jab_fungsional',
        'tmt',
        'unit_kerja'];

    public function detail_penunjang(){
        return $this->hasMany(DetailPenunjang::class, 'penunjang_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/PenunjangController.php
<?php

namespace App\Http\Controllers;

use PDF;
use App\User;
use Carbon\Carbon;
use App\Penunjang;
use App\DetailPenunjang;
use Illuminate\Http\Request;

class PenunjangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $data = Penunjang::with('user')->get();
      return view('penunjang.index')->with('data', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('penunjang.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $penunjang = Penunjang::create([
            'name' => $request->name,
            'user_id' => $request->user_id,
            'nip' => $request->nip,
            'nidn' => $request->nidn,
            'pangkat' => $request->pangkat,
            'gol_ruang' => $request->gol_ruang,
            'jab_fungsional' => $request->jab_fungsional,
            'tmt' => $request->tmt,
            'unit_kerja' => $request->unit_kerja
          ]);
          $total_price = 0;
          $penunjang_arr = [];
          for ($i=0; $i < count($request->kegiatan_penunjang); $i++) {
            $penunjang_arr[] = [
              'penunjang_id' => $penunjang->id,
              'kegiatan_penunjang' => $request->kegiatan_penunjang[$i],
              'kedudukan' => $request->kedudukan[$i],
              'tempat' => $request->tempat[$i],
              'tgl' => $request->tgl[$i],
              'jml_kredit' => $request->jml_kredit[$i],
            ];
          }
        //   return $penunjang_arr;
          if (DetailPenunjang::insert($penunjang_arr)) {
            return redirect(route('penunjang.index'));
          } else {
            return 'n';
          }
        //   return redirect(route('penunjang.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $data = Penunjang::with('detail_penunjang')->find($id);
      $a = User::where('id' , $data->user_id)->get();
      return view('penunjang.view',compact('data', 'a'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $data = DetailPenunjang::find($id);
          return view('penunjang.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $penunjang = Penunjang::find($id);
        $penunjang->name = $request->input('name');
        $penunjang->user_id = $request->input('user_id');
        $penunjang->nip = $request->input('nip');
        $penunjang->nidn = $request->input('nidn');
        $penunjang->pangkat = $request->input('pangkat');
        $penunjang->gol_ruang = $request->input('gol_ruang');
        $penunjang->jab_fungsional = $request->input('jab_fungsional');
        $penunjang->tmt = $request->input('tmt');
        $penunjang->unit_kerja = $request->input('unit_kerja');
        $penunjang->kegiatan_penunjang = $request->input('kegiatan_penunjang');
        $penunjang->kedudukan = $request->input('kedudukan');
        $penunjang->tempat = $request->input('tempat');
        $penunjang->tgl = $request->input('tgl');
        $penunjang->jml_kredit = $request->input('jml_kredit');
        $penunjang->save();

        return redirect('/penunjang')->with('success', 'Penunjang Updated');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function find(Request $request)
    {
        $data = User::where('name', $request->input('name'))->get();
        for ($i=0; $i < count($data); $i++) {
          $a = User::where('id' , $data[$i]->penanggung_jawab)->get();
        }
        return view('penunjang.create',compact('data', 'a'));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $data = Penunjang::find($id);
      $data->delete();
      return redirect('/penunjang');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy_detail($id)
    {
      $data = DetailPenunjang::find($id);
      $data->delete();
      return redirect('/penunjang');
    }

    public function update_detail(Request $request, $id)
    {
        DetailPenunjang::where('id', $id)
          ->update([
            'kegiatan_penunjang' => $request->input('kegiatan_penunjang'),
            'kedudukan' => $request->input('kedudukan'),
            'tempat' => $request->input('tempat'),
            'tgl' => $request->input('tgl'),
            'jml_kredit' => $request->input('jml_kredit'),
          ]);

        return redirect('/penunjang');
    }

    public function downloadPDF($id){
        $data = Penunjang::with('detail_penunjang')->find($id);
        $date = Carbon::now();
        if ($data->jab_fungsional == 'Asisten Ahli') {
          $kredit = (10/100)*$data->detail_penunjang->sum('jml_kredit');
        } elseif ($data->jab_fungsional == 'Lektor') {
          $kredit = (10/100)*$data->detail_penunjang->sum('jml_kredit');
        } elseif ($data->jab_fungsional == 'Lektor Kepala') {
          $kredit = (10/100)*$data->detail_penunjang->sum('jml_kredit');
        }else ($data->jab_fungsional == 'Profesor') {
          $kredit = (10/100)*$data->detail_penunjang->sum('jml_kredit')
        };
        $a = User::where('id' , $data->user_id)->get();
        $pdf = PDF::loadView('penunjang.pdf', compact('data', 'date','a', 'kredit'));
        return $pdf->stream('penunjang-'.$data->name.'.pdf');

      }
}

resources/views/penunjang/create.blade.php
@extends('layouts.app')
@section('content')
  <div class="column">
    <div class="card">
      <div class="card-header">
        <div class="columns">
          <div class="column">
            <p class="card-header-title">
              Tambah Data Penunjang
            </p>
          </div>
        </div>
      </div>
      <div class="card-content">

        @isset($data)
        <form class="form-vertical" action="{{ route('penunjang.store') }}" method="post">
              {{ csrf_field() }}
        <div class="columns">
          <div class="column">
            <div class="field">
             <label class="label">Nama Dosen</label>
             <div class="control">
                  <input type="text" name="name" class="input" value="{{$data[0]->name}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">Penanggung Jawab</label>
             <div class="control">
                  <input type="text" class="input" value="{{$a[0]->name}}" readonly>
                  <input type="hidden" name="user_id" class="input" value="{{$a[0]->id}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">NIP</label>
             <div class="control">
                  <input type="text" name="nip" class="input" value="{{$data[0]->nip}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">NIDN</label>
             <div class="control">
                  <input type="text" name="nidn" class="input" value="{{$data[0]->nidn}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">Pangkat</label>
             <div class="control">
                  <input type="text" name="pangkat" class="input" value="{{$data[0]->pangkat}}" readonly>
              </div>
            </div>
          </div>
        </div>
        <div class="columns">
          <div class="column">
            <div class="field">
             <label class="label">Gol. Ruang</label>
             <div class="control">
                  <input type="text" name="gol_ruang" class="input" value="{{$data[0]->gol_ruang}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">Jabatan Fungsional</label>
             <div class="control">
                  <input type="text" name="jab_fungsional" class="input" value="{{$data[0]->jab_fungsional}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">TMT</label>
             <div class="control">
                  <input type="text" name="tmt" class="input" value="{{$data[0]->tmt}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">Unit Kerja</label>
             <div class="control">
                  <input type="text" name="unit_kerja" class="input" value="{{$data[0]->unit_kerja}}" readonly>
              </div>
            </div>
          </div>
        </div>
        <div class="notification is-info"> Pastikan Semua Data Terisi! </div>
          <div class="card">
            <header class="card-header">
              <p class="card-header-title">
                Kegiatan Penunjang Tugas Pokok Dosen
              </p>
              <a href="#" id="plus" class="card-header-icon" aria-label="more options">
                <span class="icon">
                  <i class="fas fa-plus" aria-hidden="true"></i>
                </span>
              </a>
              <a href="#" id="minus" class="card-header-icon" aria-label="remove options">
                <span class="icon">
                  <i class="fas fa-minus" aria-hidden="true"></i>
                </span>
              </a>
            </header>
            <div class="card-content parent">
              <div class="column child">
                <div class="columns">
                  <div class="column">
                    <div class="field">
                      <label class="label">Kegiatan Penunjang Tri Dharma PT</label>
                      <div class="control">
                        <textarea class="textarea" type="text" name="kegiatan_penunjang[]"></textarea>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="columns">
                  <div class="column">
                    <div class="field">
                      <label class="label">Kedudukan / Tingkat</label>
                      <div class="control">
                        <input class="input" type="text" name="kedudukan[]">
                      </div>
                    </div>
                  </div>
                  <div class="column">
                    <div class="field">
                      <label class="label">Tempat / Instansi</label>
                      <div class="control">
                        <input class="input" type="text" name="tempat[]">
                      </div>
                    </div>
                  </div>
                  <div class="column">
                    <div class="field">
                      <label class="label">Tanggal</label>
                      <div class="control">
                        <input class="input" type="text" name="tgl[]">
                      </div>
                    </div>
                  </div>
                    <div class="column">
                    <div class="field">
                      <label class="label">Jumlah Angka Kredit</label>
                      <div class="control">
                        <input class="input" type="text" name="jml_kredit[]">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

            <div class="columns m-t-30 is-gapless">
                <div class="column">
                  <a href="{{ route('penunjang.index') }}"class="button is-danger">Cancel</a>
                </div>
                <div class="column">
                  <button class="button is-success" type="submit">Save</button>
                </div>
              </div>
            </form>
        @else
          <form class="form-vertical" action="{{ url('/penunjang/find') }}" method="post">
              {{ csrf_field() }}
              <div class="field">
                <label class="label">Nama Dosen</label>
                  <div class="control">
                  <select class="input" type="text" name="name" id="dosen"></select>
                  </div>
                </div>
                <div class="column">
                  <button class="button is-success" type="submit">Submit</button>
                </div>
          </form>
        @endisset
      </div>
    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript">
  $('#dosen').select2({
    placeholder: 'Cari',
    ajax: {
      url: '/api/dosen/search',
      dataType: 'json',
      delay: 250,
      processResults: function (data) {
        return {
          results:  $.map(data, function (item) {
            return {
              text: item.name,
              id: item.name
            }
          })
        };
      },
      cache: true
    }
  });
  $('#minus').hide();
  $('#plus').click(function(){
      $('#minus').show();
      $('.child:last').clone().appendTo('.parent');
    });
    $('#minus').click(function(){
      if ($(".child").length == 2) {
        $('.child:last').remove();
        $('#minus').hide();
      } else {
        $('.child:last').remove();
      }
    });
  </script>
@endpush

@push('style')
  <style media="screen">

  </style>
@endpush

resources/views/penunjang/edit.blade.php
@extends('layouts.app')
@section('content')
  <div class="column">
    <div class="card">
      <div class="card-header">
        <div class="columns">
          <div class="column">
            <p class="card-header-title">
              Edit Data Penunjang
            </p>
          </div>
        </div>
      </div>
      <div class="notification is-info"> Pastikan Semua Data Terisi! </div>
      <div class="card-content">
        <form class="form-vertical" action="{{ url('detail_penunjang/'.$data->id) }}" method="post">
          {{ csrf_field() }}
          @method('PUT')
          <input type="hidden" name="_method" value="PUT">
            <div class="columns">
              <div class="column">
                <div class="field">
                  <label class="label">Nama Dosen</label>
                  <div class="control">
                    <input type="text" name="name" class="input" value="{{$data->name}}" readonly>
                  </div>
                </div>
              </div>
              <div class="column">
                <div class="field">
                  <label class="label">Jabatan Fungsional</label>
                  <div class="control">
                    <input type="text" name="jab_fungsional" class="input" value="{{$data->jab_fungsional}}" readonly>
                  </div>
                </div>
              </div>
            </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Kegiatan Penunjang Tri Dharma PT</label>
                <div class="control">
                <textarea class="textarea" type="text" name="kegiatan_penunjang">{{ $data->kegiatan_penunjang }}</textarea>
              </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Kedudukan / Tingkat</label>
                <div class="control">
                  <input class="input" type="text" value="{{ $data->kedudukan }}" name="kedudukan">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Tempat / Instansi</label>
                <div class="control">
                  <input class="input" type="text" value="{{ $data->tempat }}" name="tempat">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Tanggal</label>
                <div class="control">
                  <input class="input" type="text" value="{{ $data->tgl }}" name="tgl">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Jumlah Angka Kredit</label>
                <div class="control">
                  <input class="input" type="text" value="{{ $data->jml_kredit }}" name="jml_kredit">
                </div>
              </div>
            </div>
          </div>
          <div class="columns m-t-30 is-gapless">
            <div class="column">
              <a href="{{ route('penunjang.index') }}"class="button is-danger">Cancel</a>
            </div>
            <div class="column">
              <button class="button is-success" type="submit">Save</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

@push('script')
  <script type="text/javascript">

  </script>
@endpush

@push('style')
  <style media="screen">

  </style>
@endpush

resources/views/penunjang/index.blade.php
@extends('layouts.app')

@section('content')
<div class="column">
    <div class="card">
        <div class="card-header">
                    <p class="card-header-title">
                    Kegiaatan Penunjang
                    </p>
        </div>

        <div class="card-content">
          @role(['superadministrator','admin'])
          <div class="columns">
            <a href="{{ route('penunjang.create') }}" class="button is-primary">Create</a>
          </div>
          @endrole
          <div class="table__wrapper">
            <table class="table is-bordered pricing__table is-fullwidth" id="datatable">
              <thead>
                <tr>
                  <th><abbr title="Position">No</abbr></th>
                  <th>Nama Dosen</th>
                  <th>Jabatan Fungsional</th>
                  <th>Penanggung Jawab</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
              <?php $n=1 ?>
                @foreach($data as $a)
                  <tr>
                    <th>{{ $n }}</th>
                    <td>{{ $a->name }}</td>
                    <td>{{ $a->jab_fungsional }}</td>
                    <td>{{ $a->user->name}}</td>

                      <td>
                      <div class="columns">
                        <div class="column">
                          <a href="penunjang/{{$a->id}}" class="button is-info">View</a>
                        </div>
                        @role(['superadministrator','admin'])
                          <div class="column">
                            <form action="penunjang/{{$a->id}}" method="post">
                              {{ csrf_field() }}
                              <input type="hidden" name="_method" value="delete">
                              <button type="submit" name="button" class="button is-danger">Delete</button>
                            </form>
                          </div>
                        </div>
                        @endrole
                      </td>
                  </tr>
                <?php $n++ ?>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>
@endsection

@push('scripts')
  <script type="text/javascript">
    $('#datatable').DataTable();
  </script>
@endpush

resources/views/penunjang/view.blade.php
@extends('layouts.app')
@section('content')
  <div class="column">
    <div class="card">
      <div class="card-header">
            <p class="card-header-title">
              View Data Penunjang
            </p>
            @role(['superadministrator','admin'])
            <div class="p-t-5 p-r-5">
              <a href="{{action('PenunjangController@downloadPDF', $data->id)}}"class="button is-link">Download PDF </a>
            </div>
            @endrole
        </div>
      </div>

      <div class="card-content">
        <form class="form-vertical" action="{{ url('penunjang/'.$data->id) }}" method="PUT">
          @csrf
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label class="label">Nama Dosen</label>
                        <div class="control">
                            <input type="text" name="name" class="input" value="{{$data->name}}" readonly>
                        </div>
                    </div>
                </div>
                @for($i = 0; $i < count($a); $i++)
                  @if($a[$i]->name)
                    <div class="column">
                      <div class="field">
                        <label class="label">Penanggung Jawab</label>
                        <div class="control">
                          <input class="input" type="text" name="user_id" value="{{$a[$i]->name}}" readonly>
                        </div>
                      </div>
                    </div>
                  @else

                  @endif
                @endfor
                <div class="column">
                    <div class="field">
                        <label class="label">NIP / NIDN</label>
                        <div class="control">
                            <input class="input" type="text" value="{{$data->nip}} , {{$data->nidn}}" readonly>
                        </div>
                    </div>
                </div>
            </div>
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label class="label">Pangkat / Golongan Ruang</label>
                        <div class="control">
                            <input class="input" type="text" value="{{$data->pangkat}} , {{$data->gol_ruang}}" readonly>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="field">
                        <label class="label">Jabatan Fungsional / TMT</label>
                        <div class="control">
                            <input type="text" class="input" value="{{$data->jab_fungsional}} , {{$data->tmt}}" readonly>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="field">
                        <label class="label">Unit Kerja</label>
                        <div class="control">
                            <input class="input" type="text" name="unit_kerja" value="{{$data->unit_kerja}}" readonly>
                        </div>
                    </div>
                </div>
          </div>

            <div class="notification is-info">Kegiatan Penunjang Tugas Pokok Dosen</div>
            <table class="table is-bordered pricing__table" id="datatable">
            <thead>
              <tr>
                <th>No</th>
                <th>Kegiatan Penunjang Tri Dharma PT</th>
                <th>Kedudukan / Tingkat</th>
                <th>Tempat / Instansi</th>
                <th>Tanggal</th>
                <th>Jumlah Angka Kredit</th>
                <th>Ket. / Bukti Fisik</th>
                @role(['superadministrator','admin'])
                <th>Action</th>
                @endrole
              </tr>
            </thead>
            <tbody>
              <?php $n=1 ?>
              @foreach($data->detail_penunjang as $a)
              <tr>
                <th>{{ $n }}</th>
                <td>{{ $a->kegiatan_penunjang }}</td>
                <td>{{ $a->kedudukan }}</td>
                <td>{{ $a->tempat }}</td>
                <td>{{ $a->tgl }}</td>
                <td>{{ $a->jml_kredit }}</td>
                <td>D{{ $n }}</td>
                @role(['superadministrator','admin'])
                <td>
                  <div class="columns">
                  <div class="column">
                      <a href="{!! route('penunjang.edit', $a->id) !!}" class="button is-info">Edit</a>
                    </div>

                  </div>
                </td>
                @endrole
              </tr>
              <?php $n++ ?>
              @endforeach
            </tbody>
          </table>
            </div>
        </form>
      </div>
    </div>
</div>

    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript">
    $('#datatable').DataTable();
  </script>
@endpush

@push('style')
  <style media="screen">

  </style>
@endpush