routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {
  Route::get('/home', 'HomeController@index')->name('home');

  Route::get('export', 'ExcelController@Export');

  Route::get('penelitian/excel/{type}', 'ExcelController@penelitian');

  Route::get('pengabdian/excel/{type}', 'ExcelController@pengabdian');

  Route::get('dosen/excel/{type}', 'ExcelController@dosen');

  Route::get('penunjang/excel/{type}', 'ExcelController@penunjang');

  Route::get('dupak/excel/{type}', 'ExcelController@dupak');

  Route::put('detail_penunjang/{id}', 'PenunjangController@update_detail');

  Route::delete('detail_penunjang/{id}', 'PenunjangController@destroy_detail');

  Route::put('detail_unsurpendidikan/{id}', 'UnsurPendidikanController@update_detail');

  Route::delete('detail_unsurpendidikan/{id}', 'UnsurPendidikanController@destroy_detail');

  Route::put('detail_pelaksanapendidikan/{id}', 'PelaksanaPendidikanController@update_detail');

  Route::delete('detail_pelaksanapendidikan/{id}', 'PelaksanaPendidikanController@destroy_detail');

  Route::put('detail_penelitian/{id}', 'PenelitianController@update_detail');

  Route::delete('detail_penelitian/{id}', 'PenelitianController@destroy_detail');

  Route::put('detail_pengabdian/{id}', 'PengabdianController@update_detail');

  Route::delete('detail_pengabdian/{id}', 'PengabdianController@destroy_detail');

  Route::post('penelitian/find', 'PenelitianController@find');

  Route::post('penunjang/find', 'PenunjangController@find');

  Route::post('pengabdian/find', 'PengabdianController@find');

  Route::post('unsurpendidikan/find', 'UnsurPendidikanController@find');

  Route::post('pelaksanapendidikan/find', 'PelaksanaPendidikanController@find');

  Route::resource('dosen', 'DosenController');

  Route::resource('penelitian_detail', 'DetailPenelitianController');

  Route::resource('unsurpendidikan', 'UnsurPendidikanController');

  Route::resource('pendidikan', 'PendidikanController');

  Route::resource('pelaksanapendidikan', 'PelaksanaPendidikanController');

  Route::resource('penelitian', 'PenelitianController');

  Route::resource('pengabdian', 'PengabdianController');

  Route::resource('penunjang', 'PenunjangController');

  Route::resource('dupak', 'DupakController');

  Route::get('penelitian/downloadPDF/{id}','PenelitianController@downloadPDF');

  Route::get('pengabdian/downloadPDF/{id}','PengabdianController@downloadPDF');

  Route::get('penunjang/downloadPDF/{id}','PenunjangController@downloadPDF');

  Route::get('pendidikan/downloadPDF/{id}','PendidikanController@downloadPDF');

  Route::get('dupak/downloadPDF/{id}','DupakController@downloadPDF');
});

resources/views/_includes/aside.blade.php
@role(['superadministrator','admin', 'dosen'])
  <aside class="column is-2 aside is-hidden-mobile is-clearfix">
  <nav class="menu">
    <p class="menu-label"></p>
    <ul class="menu-list is-tab">
      <li><a href="{{ url('/') }}"><span class="icon is-small"><i class="fas fa-home"></i></span> Home</a></li>
    </ul>
    @role(['superadministrator','admin'])
    <p class="menu-label"> General</p>
    <ul class="menu-list is-tab">
      <li><a href="{{ route('dosen.index') }}"><span class="icon is-small"><i class="fas fa-users"></i></span> Dosen</a></li>
    </ul>
    @endrole

    <p class="menu-label">
      Master
    </p>
    <ul class="menu-list is-tab">
      <li>
      <li><a href="{{ route('pendidikan.index') }}"><span class="icon is-small"><i class="fas fa-bookmark"></i></span> Pendidikan</a>
        @role(['superadministrator','admin'])
      <ul>
      <li><a href="{{ route('unsurpendidikan.index') }}">Unsur Pendidikan</a></li>
      <li><a href="{{ route('pelaksanapendidikan.index') }}">Unsur Pelaksanaan Pendidikan</a></li>
      </ul>
      @endrole
      </li>
      <li><a href="{{ route('penelitian.index') }}"><span class="icon is-small"><i class="fas fa-bookmark"></i></span>  Penelitian</a></li>
      <li><a href="{{ route('pengabdian.index') }}"><span class="icon is-small"><i class="fas fa-bookmark"></i></span>  Pengabdian</a></li>
      <li><a href="{{ route('penunjang.index') }}"><span class="icon is-small"><i class="fas fa-bookmark"></i></span>  Penunjang</a></li>
      <li><a href="{{ route('dupak.index') }}"><span class="icon is-small"><i class="fas fa-bookmark"></i></span> Dupak</a></li>
      </li>
    </ul>

    <!-- @role('superadministrator')
      <p class="menu-label">
        Role Settings
      </p>
      <ul class="menu-list is-tab">
        <li><a href=""><span class="icon is-small"><i class="fas fa-users"></i></span> Management</a></li>
      </ul>
    @endrole -->
  </nav>
</aside>
@endrole

resources/views/_includes/navbar.blade.php
<header>
  <div class="hero-head">
    <nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">

        <a class="navbar-item is--brand">
          {{ config('app.name', 'Jafunng') }}
        </a>

        <button class="button navbar-burger" data-target="navMenu">
          <span></span>
          <span></span>
          <span></span>
        </button>

      </div>


      <div class="navbar-menu navbar-end" id="navMenu">
        @if (Auth::guest())
          <a class="navbar-item nav-tag" href="{{ route('login') }}">
            <span class="icon is-small">
              <i class="fas fa-lock"></i>
            </span>
            
          </a>
        @else
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <figure class="image is-32x32" style="margin-right:.5em;">
                <span class="icon is-medium"><i class="far fa-user-circle"></i></span>
              </figure>
              {{ Auth::user()->name }}
            </a>

            <div class="navbar-dropdown is-right">
                <a class="navbar-item"
                   onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                    Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                      style="display: none;">
                    {{ csrf_field() }}
                </form>
            </div>
          </div>
        @endif
      </div>
    </nav>
  </div>
</header>