routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {
  Route::get('/home', 'HomeController@index')->name('home');

  Route::get('export', 'ExcelController@Export');

  Route::get('penelitian/excel/{type}', 'ExcelController@penelitian');

  Route::get('pengabdian/excel/{type}', 'ExcelController@pengabdian');

  Route::get('dosen/excel/{type}', 'ExcelController@dosen');

  Route::get('penunjang/excel/{type}', 'ExcelController@penunjang');

  Route::get('dupak/excel/{type}', 'ExcelController@dupak');

  Route::put('detail_penunjang/{id}', 'PenunjangController@update_detail');

  Route::delete('detail_penunjang/{id}', 'PenunjangController@destroy_detail');

  Route::put('detail_unsurpendidikan/{id}', 'UnsurPendidikanController@update_detail');

  Route::delete('detail_unsurpendidikan/{id}', 'UnsurPendidikanController@destroy_detail');

  Route::put('detail_pelaksanapendidikan/{id}', 'PelaksanaPendidikanController@update_detail');

  Route::delete('detail_pelaksanapendidikan/{id}', 'PelaksanaPendidikanController@destroy_detail');

  Route::put('detail_penelitian/{id}', 'PenelitianController@update_detail');

  Route::delete('detail_penelitian/{id}', 'PenelitianController@destroy_detail');

  Route::put('detail_pengabdian/{id}', 'PengabdianController@update_detail');

  Route::delete('detail_pengabdian/{id}', 'PengabdianController@destroy_detail');

  Route::post('penelitian/find', 'PenelitianController@find');

  Route::post('penunjang/find', 'PenunjangController@find');

  Route::post('pengabdian/find', 'PengabdianController@find');

  Route::post('unsurpendidikan/find', 'UnsurPendidikanController@find');

  Route::post('pelaksanapendidikan/find', 'PelaksanaPendidikanController@find');

  Route::resource('dosen', 'DosenController');

  Route::resource('penelitian_detail', 'DetailPenelitianController');

  Route::resource('unsurpendidikan', 'UnsurPendidikanController');

  Route::resource('pendidikan', 'PendidikanController');

  Route::resource('pelaksanapendidikan', 'PelaksanaPendidikanController');

  Route::resource('penelitian', 'PenelitianController');

  Route::resource('pengabdian', 'PengabdianController');

  Route::resource('penunjang', 'PenunjangController');

  Route::resource('dupak', 'DupakController');

  Route::get('penelitian/downloadPDF/{id}','PenelitianController@downloadPDF');

  Route::get('pengabdian/downloadPDF/{id}','PengabdianController@downloadPDF');

  Route::get('penunjang/downloadPDF/{id}','PenunjangController@downloadPDF');

  Route::get('pendidikan/downloadPDF/{id}','PendidikanController@downloadPDF');

  Route::get('dupak/downloadPDF/{id}','DupakController@downloadPDF');
});

app/UnsurPendidikan.php
<?php

namespace App;

use App\DetailUnsurPendidikan;
use Illuminate\Database\Eloquent\Model;

class UnsurPendidikan extends Model
{
    protected $table = 'unsurpendidikans';

    protected $fillable = [
        'user_id',
        'name',
        'nip',
        'nidn',
        'pangkat',
        'gol_ruang',
        'jab_fungsional',
        'tmt',
        'unit_kerja'];

    public function detail_unsurpendidikan(){
        return $this->hasMany(DetailUnsurPendidikan::class, 'unsurpendidikan_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/UnsurPendidikanController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\UnsurPendidikan;
use App\DetailUnsurPendidikan;
use Illuminate\Http\Request;

class UnsurPendidikanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $data = UnsurPendidikan::with('user')->get();
      return view('unsurpendidikan.index')->with('data', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('unsurpendidikan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $unsurpendidikan = UnsurPendidikan::create([
            'name' => $request->name,
            'user_id' => $request->user_id,
            'nip' => $request->nip,
            'nidn' => $request->nidn,
            'pangkat' => $request->pangkat,
            'gol_ruang' => $request->gol_ruang,
            'jab_fungsional' => $request->jab_fungsional,
            'tmt' => $request->tmt,
            'unit_kerja' => $request->unit_kerja
          ]);
          $total_price = 0;
          $unsurpendidikan_arr = [];
          for ($i=0; $i < count($request->kegiatan_pend); $i++) {
            $unsurpendidikan_arr[] = [
              'unsurpendidikan_id' => $unsurpendidikan->id,
              'kegiatan_pend' => $request->kegiatan_pend[$i],
              'tempat' => $request->tempat[$i],
              'tgl' => $request->tgl[$i],
              'jml_kredit' => $request->jml_kredit[$i],
            ];
          }
        //   return $unsurpendidikan_arr;
          if (DetailUnsurPendidikan::insert($unsurpendidikan_arr)) {
            return redirect(route('unsurpendidikan.index'));
          } else {
            return 'n';
          }
        //   return redirect(route('unsurpendidikan.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $data = UnsurPendidikan::with('detail_unsurpendidikan')->find($id);
      $a = User::where('id' , $data->user_id)->get();
      return view('unsurpendidikan.view',compact('data', 'a'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $data = DetailUnsurPendidikan::find($id);
          return view('unsurpendidikan.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $unsurpendidikan = UnsurPendidikan::find($id);
        $unsurpendidikan->name = $request->input('name');
        $unsurpendidikan->user_id = $request->input('user_id');
        $unsurpendidikan->nip = $request->input('nip');
        $unsurpendidikan->nidn = $request->input('nidn');
        $unsurpendidikan->pangkat = $request->input('pangkat');
        $unsurpendidikan->gol_ruang = $request->input('gol_ruang');
        $unsurpendidikan->jab_fungsional = $request->input('jab_fungsional');
        $unsurpendidikan->tmt = $request->input('tmt');
        $unsurpendidikan->kegiatan_pend = $request->input('kegiatan_pend');
        $unsurpendidikan->tempat = $request->input('tempat');
        $unsurpendidikan->tgl = $request->input('tgl');
        $unsurpendidikan->jml_kredit = $request->input('jml_kredit');
        $unsurpendidikan->save();

        return redirect('/unsurpendidikan')->with('success', 'UnsurPendidikan Updated');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function find(Request $request)
    {
        $data = User::where('name', $request->input('name'))->get();
        for ($i=0; $i < count($data); $i++) {
          $a = User::where('id' , $data[$i]->penanggung_jawab)->get();
        }
        return view('unsurpendidikan.create',compact('data', 'a'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $id = UnsurPendidikan::find($id);
      $id->delete();
      return redirect('/unsurpendidikan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy_detail($id)
    {
      $data = DetailUnsurPendidikan::find($id);
      $data->delete();
      return redirect('/unsurpendidikan');
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function update_detail(Request $request, $id)
   {
       DetailUnsurPendidikan::where('id', $id)
         ->update([
           'kegiatan_pend' => $request->input('kegiatan_pend'),
           'tempat' => $request->input('tempat'),
           'tgl' => $request->input('tgl'),
           'jml_kredit' => $request->input('jml_kredit'),
         ]);

       return redirect('/unsurpendidikan');
   }

}

resources/views/unsurpendidikan/create.blade.php
@extends('layouts.app')
@section('content')
  <div class="column">
    <div class="card">
      <div class="card-header">
        <div class="columns">
          <div class="column">
            <p class="card-header-title">
              Tambah Data Unsur Pendidikan
            </p>
          </div>
        </div>
      </div>
      <div class="card-content">

        @isset($data)
        <form class="form-vertical" action="{{ route('unsurpendidikan.store') }}" method="post">
              {{ csrf_field() }}
              @for($i = 0; $i < count($a); $i++)
                @if($a[$i]->name)
        <div class="columns">
          <div class="column">
            <div class="field">
             <label class="label">Nama Dosen</label>
             <div class="control">
                  <input type="text" name="name" class="input" value="{{$data[0]->name}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">Penanggung Jawab</label>
             <div class="control">
                  <input type="text" class="input" value="{{$a[0]->name}}" readonly>
                  <input type="hidden" name="user_id" class="input" value="{{$a[0]->id}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">NIP</label>
             <div class="control">
                  <input type="text" name="nip" class="input" value="{{$data[0]->nip}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">NIDN</label>
             <div class="control">
                  <input type="text" name="nidn" class="input" value="{{$data[0]->nidn}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">Pangkat</label>
             <div class="control">
                  <input type="text" name="pangkat" class="input" value="{{$data[0]->pangkat}}" readonly>
              </div>
            </div>
          </div>
        </div>
        <div class="columns">
          <div class="column">
            <div class="field">
             <label class="label">Gol. Ruang</label>
             <div class="control">
                  <input type="text" name="gol_ruang" class="input" value="{{$data[0]->gol_ruang}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">Jabatan Fungsional</label>
             <div class="control">
                  <input type="text" name="jab_fungsional" class="input" value="{{$data[0]->jab_fungsional}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">TMT</label>
             <div class="control">
                  <input type="text" name="tmt" class="input" value="{{$data[0]->tmt}}" readonly>
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
             <label class="label">Unit Kerja</label>
             <div class="control">
                  <input type="text" name="unit_kerja" class="input" value="{{$data[0]->unit_kerja}}" readonly>
              </div>
            </div>
          </div>
        </div>
        @else

        @endif
      @endfor
      <div class="notification is-info"> Pastikan Semua Data Terisi! </div>
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">
              Kegiatan Pendidikan dan Pengajaran
            </p>
            <a href="#" id="plus" class="card-header-icon" aria-label="more options">
              <span class="icon">
                <i class="fas fa-plus" aria-hidden="true"></i>
              </span>
            </a>
            <a href="#" id="minus" class="card-header-icon" aria-label="remove options">
              <span class="icon">
                <i class="fas fa-minus" aria-hidden="true"></i>
              </span>
            </a>
          </header>
          <div class="card-content parent">
            <div class="column child">
              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Kegiatan Pendidikan dan Pengajaran</label>
                    <div class="control">
                      <textarea class="textarea" type="text" name="kegiatan_pend[]"></textarea>
                    </div>
                  </div>
                </div>
              </div>
              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Tempat / Instansi</label>
                    <div class="control">
                      <input class="input" type="text" name="tempat[]">
                    </div>
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Tanggal </label>
                    <div class="control">
                      <input class="input" type="text" name="tgl[]">
                    </div>
                  </div>
                </div>
                  <div class="column">
                  <div class="field">
                    <label class="label">Jumlah Angka Kredit</label>
                    <div class="control">
                      <input class="input" type="text" name="jml_kredit[]">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

          <div class="columns m-t-30 is-gapless">
              <div class="column">
                <a href="{{ route('unsurpendidikan.index') }}"class="button is-danger">Cancel</a>
              </div>
              <div class="column">
                <button class="button is-success" type="submit">Save</button>
              </div>
            </div>
          </form>
        @else
          <form class="form-vertical" action="{{ url('/unsurpendidikan/find') }}" method="post">
              {{ csrf_field() }}
              <div class="field">
                <label class="label">Nama Dosen</label>
                  <div class="control">
                  <select class="input" type="text" name="name" id="dosen"></select>
                  </div>
                </div>
                <div class="column">
                  <button class="button is-success" type="submit">Submit</button>
                </div>
          </form>
        @endisset
      </div>
    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript">
  $('#dosen').select2({
    placeholder: 'Cari',
    ajax: {
      url: '/api/dosen/search',
      dataType: 'json',
      delay: 250,
      processResults: function (data) {
        return {
          results:  $.map(data, function (item) {
            return {
              text: item.name,
              id: item.name
            }
          })
        };
      },
      cache: true
    }
  });
  $('#minus').hide();
  $('#plus').click(function(){
      $('#minus').show();
      $('.child:last').clone().appendTo('.parent');
    });
    $('#minus').click(function(){
      if ($(".child").length == 2) {
        $('.child:last').remove();
        $('#minus').hide();
      } else {
        $('.child:last').remove();
      }
    });
  </script>
@endpush

@push('style')
  <style media="screen">

  </style>
@endpush

resources/views/unsurpendidikan/edit.blade.php
@extends('layouts.app')
@section('content')
  <div class="column">
    <div class="card">
      <div class="card-header">
        <div class="columns">
          <div class="column">
            <p class="card-header-title">
              Edit Data Unsur Pendidikan
            </p>
          </div>
        </div>
      </div>
      <div class="notification is-info"> Pastikan Semua Data Terisi! </div>
      <div class="card-content">
        <form class="form-vertical" action="{{ url('detail_unsurpendidikan/'.$data->id) }}" method="post">
          {{ csrf_field() }}
          @method('PUT')
          <input type="hidden" name="_method" value="PUT">
            <div class="columns">
              <div class="column">
                <div class="field">
                  <label class="label">Nama Dosen</label>
                  <div class="control">
                    <input type="text" name="name" class="input" value="{{$data->name}}" readonly>
                  </div>
                </div>
              </div>
              <div class="column">
                <div class="field">
                  <label class="label">Jabatan Fungsional</label>
                  <div class="control">
                    <input type="text" name="jab_fungsional" class="input" value="{{$data->jab_fungsional}}" readonly>
                  </div>
                </div>
              </div>
            </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Kegiatan Pendidikan dan Pengajaran</label>
                <div class="control">
                <textarea class="textarea" type="text" name="kegiatan_pend">{{ $data->kegiatan_pend }}</textarea>
              </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <label class="label">Tempat / Instansi</label>
                <div class="control">
                  <input class="input" type="text" value="{{ $data->tempat }}" name="tempat">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Tanggal</label>
                <div class="control">
                  <input class="input" type="text" value="{{ $data->tgl }}" name="tgl">
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <label class="label">Jumlah Angka Kredit</label>
                <div class="control">
                  <input class="input" type="text" value="{{ $data->jml_kredit }}" name="jml_kredit">
                </div>
              </div>
            </div>
          </div>
          <div class="columns m-t-30 is-gapless">
            <div class="column">
              <a href="{{ route('unsurpendidikan.index') }}"class="button is-danger">Cancel</a>
            </div>
            <div class="column">
              <button class="button is-success" type="submit">Save</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

@push('script')
  <script type="text/javascript">

  </script>
@endpush

@push('style')
  <style media="screen">

  </style>
@endpush

resources/views/unsurpendidikan/index.blade.php
@extends('layouts.app')

@section('content')
<div class="column">
    <div class="card">
        <div class="card-header">
                    <p class="card-header-title">
                    Kegiatan Unsur Pendidikan
                    </p>
        </div>

        <div class="card-content">
          @role(['superadministrator','admin'])
          <div class="columns">
            <a href="{{ route('unsurpendidikan.create') }}" class="button is-primary">Create</a>
          </div>
          @endrole
          <div class="table__wrapper">
            <table class="table is-bordered pricing__table is-fullwidth" id="datatable">
              <thead>
                <tr>
                  <th><abbr title="Position">No</abbr></th>
                  <th>Nama Dosen</th>
                  <th>Jabatan Fungsional</th>
                  <th>Penanggung Jawab</th>
                  @role(['superadministrator','admin'])
                  <th>Action</th>
                  @endrole
                </tr>
              </thead>
              <tbody>
              <?php $n=1 ?>
                @foreach($data as $a)
                  <tr>
                    <th>{{ $n }}</th>
                    <td>{{ $a->name }}</td>
                    <td>{{ $a->jab_fungsional }}</td>
                    <td>{{ $a->user->name}}</td>
                    @role(['superadministrator','admin'])
                      <td>
                      <div class="columns">
                        <div class="column">
                          <a href="unsurpendidikan/{{$a->id}}" class="button is-info">View</a>
                        </div>
                          <div class="column">
                            <form action="unsurpendidikan/{{$a->id}}" method="post">
                              {{ csrf_field() }}
                              <input type="hidden" name="_method" value="delete">
                              <button type="submit" name="button" class="button is-danger">Delete</button>
                            </form>
                          </div>
                        </div>
                      </td>
                    @endrole
                  </tr>
                <?php $n++ ?>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>
@endsection

@push('scripts')
  <script type="text/javascript">
    $('#datatable').DataTable();
  </script>
@endpush

resources/views/unsurpendidikan/view.blade.php
@extends('layouts.app')
@section('content')
<div class="column">
    <div class="card">
        <div class="card-header">
          <p class="card-header-title">
            Kegiatan Unsur Pendidikan
          </p>
        </div>

      <div class="card-content">
        <form class="form-vertical" action="{{ url('unsurpendidikan/'.$data->id) }}" method="PUT">
          @csrf
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label class="label">Nama Dosen</label>
                        <div class="control">
                            <input type="text" name="name" class="input" value="{{$data->name}}" readonly>
                        </div>
                    </div>
                </div>
                @for($i = 0; $i < count($a); $i++)
                  @if($a[$i]->name)
                    <div class="column">
                      <div class="field">
                        <label class="label">Penanggung Jawab</label>
                        <div class="control">
                          <input class="input" type="text" name="user_id" value="{{$a[$i]->name}}" readonly>
                        </div>
                      </div>
                    </div>
                  @else

                  @endif
                @endfor
                <div class="column">
                    <div class="field">
                        <label class="label">NIP / NIDN</label>
                        <div class="control">
                            <input class="input" type="text" value="{{$data->nip}} , {{$data->nidn}}" readonly>
                        </div>
                    </div>
                </div>
            </div>
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label class="label">Pangkat / Golongan Ruang</label>
                        <div class="control">
                            <input class="input" type="text" value="{{$data->pangkat}} , {{$data->gol_ruang}}" readonly>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="field">
                        <label class="label">Jabatan Fungsional / TMT</label>
                        <div class="control">
                            <input type="text" class="input" value="{{$data->jab_fungsional}} , {{$data->tmt}}" readonly>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="field">
                        <label class="label">Unit Kerja</label>
                        <div class="control">
                            <input class="input" type="text" name="unit_kerja" value="{{$data->unit_kerja}}" readonly>
                        </div>
                    </div>
                </div>
          </div>

            <div class="notification is-info"> Kegiatan Pendidikan dan Pengajaran</div>
            <table class="table is-bordered pricing__table" id="datatable">
            <thead>
              <tr>
                <th>No</th>
                <th>Kegiatan Pendidikan dan Pengajaran</th>
                <th>Tempat / Instansi</th>
                <th>Tanggal</th>
                <th>Jumlah Angka Kredit</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <?php $n=1 ?>
              @foreach($data->detail_unsurpendidikan as $a)
              <tr>
                <th>{{ $n }}</th>
                <td>{{ $a->kegiatan_pend }}</td>
                <td>{{ $a->tempat }}</td>
                <td>{{ $a->tgl }}</td>
                <td>{{ $a->jml_kredit }}</td>
                <td>
                  <div class="columns">
                    <div class="column">
                        <a href="{!! route('unsurpendidikan.edit', $a->id) !!}" class="button is-info">Edit</a>
                    </div>
                  </div>
                </td>
              </tr>

              <?php $n++ ?>
              @endforeach
            </tbody>
          </table>


            </div>
            </div>
        </form>
      </div>
    </div>
</div>

    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript">
    $('#datatable').DataTable();
  </script>
@endpush

@push('style')
  <style media="screen">

  </style>
@endpush